export const sampleOwnerList = [
  {
    age: 22,
    id: 1,
    name: 'Liz',
    gender: 'male',
    company: 'EMTRAC',
    email: 'emersonmelendez@emtrac.com',
    phone: '+1 (828) 461-2061',
    address: '291 Oak Street, Stevens, Maine, 5447',
    about:
      'Do elit irure incididunt eiusmod deserunt aliqua nulla enim Lorem anim in mollit exercitation veniam. Ex incididunt aute aliquip minim fugiat nulla excepteur tempor eiusmod. Ut ea veniam minim cupidatat fugiat enim aliquip ipsum aliquip. Sunt ea Lorem elit laboris occaecat deserunt cillum nostrud. Cillum magna duis nisi minim proident irure mollit. Cillum consequat ullamco exercitation labore sunt tempor laboris cillum consequat laboris qui duis eu laborum. Nisi dolore id et anim laborum nostrud.\r\n',
    registered: '2015-11-16T08:42:22 -08:00',
    favoriteFruit: 'banana',
  },
  {
    age: 29,
    id: 2,
    name: 'Lowe',
    gender: 'male',
    company: 'AQUAFIRE',
    email: 'emersonmelendez@aquafire.com',
    phone: '+1 (806) 452-2326',
    address: '128 Erasmus Street, Noxen, West Virginia, 5349',
    about:
      'Dolore laboris elit sunt anim. Reprehenderit amet ullamco amet ipsum magna mollit sunt. Dolore cupidatat ad eiusmod duis elit dolor. Eu cillum occaecat consectetur cillum ipsum adipisicing eu tempor pariatur nisi adipisicing non eu. Elit minim do eiusmod dolore voluptate ad cillum adipisicing aliquip dolore consectetur ea velit mollit. Non anim velit labore adipisicing sint. Occaecat laborum fugiat culpa veniam id proident.\r\n',
    registered: '2016-06-11T04:49:23 -08:00',
    favoriteFruit: 'banana',
  },
  {
    age: 28,
    id: 3,
    name: 'Angeline',
    gender: 'male',
    company: 'ESCHOIR',
    email: 'emersonmelendez@eschoir.com',
    phone: '+1 (982) 533-3474',
    address: '875 Everit Street, Iberia, Minnesota, 4301',
    about:
      'Aliqua labore dolore voluptate aute nisi ex tempor est irure consectetur incididunt et magna minim. Esse reprehenderit ex deserunt amet. Nisi pariatur id velit elit labore. Minim aliquip nostrud aliqua voluptate esse commodo. In eiusmod consectetur do non eu pariatur amet incididunt et labore ad fugiat sint amet.\r\n',
    registered: '2020-01-26T10:32:19 -08:00',
    favoriteFruit: 'apple',
  },
  {
    age: 37,
    id: 4,
    name: 'Downs',
    gender: 'male',
    company: 'TECHMANIA',
    email: 'emersonmelendez@techmania.com',
    phone: '+1 (970) 422-2743',
    address: '402 Manhattan Avenue, Dunbar, Alaska, 4745',
    about:
      'Sit non magna ex aliquip amet irure pariatur velit veniam veniam mollit ad nulla. Ex voluptate reprehenderit aliquip eiusmod aliquip officia quis deserunt elit velit. Esse laboris mollit pariatur labore aliquip in aliqua id.\r\n',
    registered: '2015-10-28T11:41:09 -08:00',
    favoriteFruit: 'apple',
  },
  {
    age: 24,
    id: 5,
    name: 'Mcfarland',
    gender: 'male',
    company: 'ILLUMITY',
    email: 'emersonmelendez@illumity.com',
    phone: '+1 (878) 508-2655',
    address: '616 Tech Place, Rivera, Montana, 2347',
    about:
      'Eu fugiat aute incididunt commodo adipisicing ullamco. Sunt eiusmod mollit id adipisicing pariatur pariatur aliquip consequat sit nisi sit. Sint aliquip ea ex commodo nisi ad. Non labore amet commodo eiusmod amet fugiat cillum ad irure enim tempor consectetur esse. Culpa ut amet do est.\r\n',
    registered: '2018-06-18T04:14:46 -08:00',
    favoriteFruit: 'strawberry',
  },
  {
    age: 23,
    id: 6,
    name: 'Alisa',
    gender: 'male',
    company: 'TALKALOT',
    email: 'emersonmelendez@talkalot.com',
    phone: '+1 (814) 521-3851',
    address: '771 College Place, Warsaw, Kansas, 1618',
    about:
      'Ea fugiat mollit nisi et. Ipsum nulla cillum cillum voluptate reprehenderit culpa cillum dolor ex sint ad cillum Lorem et. Quis occaecat adipisicing pariatur ad eiusmod nisi id minim. Cillum laborum id ullamco eiusmod deserunt.\r\n',
    registered: '2017-04-05T10:53:03 -08:00',
    favoriteFruit: 'apple',
  },
  {
    age: 40,
    id: 7,
    name: 'Rita',
    gender: 'male',
    company: 'SONGBIRD',
    email: 'emersonmelendez@songbird.com',
    phone: '+1 (811) 588-2405',
    address: '672 Brightwater Avenue, Bordelonville, Illinois, 5321',
    about:
      'Ea ad adipisicing pariatur laborum cupidatat minim ipsum minim labore laboris aliquip voluptate. Voluptate non eiusmod commodo ipsum commodo consectetur non eiusmod tempor qui. Et id irure sit magna occaecat. Sunt exercitation deserunt nulla enim excepteur deserunt.\r\n',
    registered: '2016-07-02T06:00:30 -08:00',
    favoriteFruit: 'apple',
  },
  {
    age: 25,
    id: 8,
    name: 'Mooney',
    gender: 'male',
    company: 'FUELTON',
    email: 'emersonmelendez@fuelton.com',
    phone: '+1 (925) 461-2100',
    address: '800 Brown Street, Cashtown, Louisiana, 3276',
    about:
      'Laborum enim id non fugiat dolore do aliqua cupidatat irure quis incididunt non. Minim magna aliquip amet officia nostrud nulla reprehenderit reprehenderit ut sit. Sunt commodo amet magna enim nulla duis. In laboris proident do proident laborum velit irure duis qui consectetur.\r\n',
    registered: '2019-10-07T02:29:11 -08:00',
    favoriteFruit: 'apple',
  },
  {
    age: 25,
    id: 9,
    name: 'Jacobs',
    gender: 'male',
    company: 'MAGNEMO',
    email: 'emersonmelendez@magnemo.com',
    phone: '+1 (880) 594-2333',
    address: '427 Mayfair Drive, Villarreal, Arkansas, 8395',
    about:
      'Lorem pariatur mollit fugiat veniam. Commodo in id labore cupidatat ex sint id consequat culpa anim. Ea nostrud et exercitation ea quis consequat occaecat ipsum duis eu est. Qui consectetur ipsum dolore velit id voluptate ut culpa eu dolor. Cillum nulla duis pariatur velit labore mollit proident laboris et irure ullamco dolor duis.\r\n',
    registered: '2017-03-16T02:34:26 -08:00',
    favoriteFruit: 'strawberry',
  },
];
